### ISSUE TITLE
comment lines of tsx is incorrect

### ISSUE THREAD

**Issue by a1156883061** [uctakeoff/vscode-counter#51] opened 2021-09-24 02:49 UTC
In tsx files, comment in element was not counted.
```
      {/* Bulletin Board Card */}
      <BulletinBoardCard
        title={title}
        content={content}
        address={address}
        contributor={contributor}
        publishStart={publishStart}
        publishEnd={publishEnd}
        onClick={onClick}
      />
```
comment like  `{/* Bulletin Board Card*/}` was not recognized to comment.

**Comment by a1156883061** [comment] 2021-09-24 06:06
It seems these line cause this miss
https://github.com/uctakeoff/vscode-counter/blob/627554d7ce33a3137732574bdf50ce262ea589c4/src/LineCounter.ts#L57-L63

this block comment not start with `/*` but `{/*`, so `index` not equals to `0`

So `type` was be recognized as code ranther than comment

**Comment by uctakeoff** [comment] 2021-10-02 07:29
Thank you for identifying the cause.
However, there are still some problems with your idea.

If I fix it, the following code will also become a comment line.
```
x = 0;  /* comment */
```
Some C writers often write this kind of code.

There is also a way to mark the space between `{/*` and `*/}` as a block comment, but it is not so cool.
Do you have any other ideas?

**Comment by hyluo1** [comment] 2021-10-08 01:32
I think there should be a regex to identify the tsx comment
Like this `\{.*\/\*.*\*\/.*\}`

**Comment by uctakeoff** [comment] 2022-04-13 12:59
@a1156883061  @hyluo1 
This has been fixed in ver. 3.0.4. We had no choice but to give it a special treatment after all.

**Closed** 2022-04-24 11:40 UTC
